global:
  external_labels:
    monitor: codelab-monitor
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - labels:
      alias: relay1
      type: cardano-node
    targets:
    - relay1:12798
  - labels:
      alias: producing1
      type: cardano-node
    targets:
    - producing1:12798
