#!/bin/bash

# We run a syncing node which is needed to query the blockchain for creating and registering the keys and certificates.
# Then synchronously we start creating and registering the keys.
source /scripts/functions/create_and_register_pool
create_and_register_pool
