#!/bin/bash

source /scripts/init_node_vars

function run_stakingnode {
    source /scripts/functions/run_stakingnode
    run_stakingnode
}

function run_node {
    source /scripts/functions/run_node
    run_node
}

function check_for_files {
    unset MISSING_FILES

    # Check for required files
    if [ ! -f "${NODE_PATH}/staking/pool-keys/kes.skey" ]; then
        echo "Missing required kes.skey."
        MISSING_FILES=1
    fi

    if [ ! -f "${NODE_PATH}/staking/pool-keys/vrf.skey" ]; then
        echo "Missing required vrf.skey."
        MISSING_FILES=1
    fi

    if [ ! -f "${NODE_PATH}/staking/pool-keys/node.cert" ]; then
        echo "Missing required node.cert."
        MISSING_FILES=1
    fi

    if [ ! -f "${NODE_PATH}/staking/transactions/register_stake_address.submitted" ]; then
        echo "Stake pool address has not been sent to the blockchain"
        MISSING_FILES=1
    fi

    if [ ! -f "${NODE_PATH}/staking/transactions/register_stake_pool.submitted" ]; then
        echo "Node certificate has not been sent to the blockchain"
        MISSING_FILES=1
    fi

    if [ ! -f "${NODE_PATH}/staking/POOL_ID" ]; then
        echo "Missing required POOL_ID."
        MISSING_FILES=1
    fi
}

check_for_files
if [ -n "$MISSING_FILES" ]; then
    echo "You are missing required files to start."
    echo "You need to exec into the pod to initialize the stake pool keys, addresses and certificates and submit them to the blockchain first."
    echo "You can do that by running \`create_stakepool\`"
    echo "In the meantime, we're running the stakingnode you'll need to exec into the pod to manually run this"
    run_node
else
    run_stakingnode
fi